## Preparations:

In [ ]:
import numpy as np
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

iris = datasets.load_iris()
X = iris['data'][:, (2,3)]
y = (iris['target']==2).astype(np.float64)              # 1/0 vector

## Linear SVM classification with soft margin:

In [ ]:
from sklearn.svm import LinearSVC

svm_clf = Pipeline([
    ('scaler', StandardScaler()),
    ('svm_clf', LinearSVC(C = 1, loss = 'hinge'))       # C: ’分界线‘的宽度。C小对应的更宽分界线，更有泛化能力。C大对应更窄的分界线，更容易overfit。
])
svm_clf.fit(X, y)                                       # 训练一个二分类SVM模型，先对输入数据进行standard scale

svm_clf.predict([[5.5, 1.7]])

array([1.])

## Nonlinear SVM classification with polynomial kernel:
using polynomial kernel can avoid adding too many higher degree terms which may slow down the model but getting similar results. It is generally more preferred due to higher efficiency. However, it requires parameter tunning, which can be achieved using gridsearch method.

In [ ]:
from sklearn.svm import SVC

poly_kernel_svm_clf = Pipeline([
    ('scaler', StandardScaler()),
    ('svm_clf', SVC(kernel="poly", degree=3, coef0=1, C=5)),        # kernel = 'poly': 使用polynomial kernel。degree:越小弯曲越少，分界线越简单；越大弯曲越多，分界线更复杂。coef0:更大值对应更重视低阶特征，更小值对应更重视高阶特征
])
poly_kernel_svm_clf.fit(X, y)

poly_kernel_svm_clf.predict([[5.5, 1.7]])

array([1.])

## Nonlinear SVM classification with RBF kernel:

In [ ]:
rbf_kernel_svm_clf = Pipeline([
    ("scaler", StandardScaler()),
    ("svm_clf", SVC(kernel="rbf", gamma=5, C=0.001))                # gamma:控制每一个训练数据点的影响范围，gamma小对应每个点影响范围大, vise versa。C: 控制模型容错，C小对应更加包容,vise versa。
 ])
rbf_kernel_svm_clf.fit(X, y)

rbf_kernel_svm_clf.predict([[5.5, 1.7]])

array([0.])

## SVM regression for linear tasks:

In [ ]:
from sklearn.svm import LinearSVR
svr_reg = LinearSVR(epsilon = 1.5)              # epsilon determines the width of the tube.
svr_reg.fit(X,y)

## SVM regression for nonlinear tasks:

In [ ]:
from sklearn.svm import SVR
svr_poly_reg = SVR(kernel="poly", degree=2, C=100, epsilon=0.1)
svr_poly_reg.fit(X, y)